### PR TITLE
Add filter for mods requirements

### LINKED ISSUE #147: [Request] Filter for requirements
An option to quickly find maps that make use of Chroma/MappingExtensions/NoodeExtensions would be great.
I suspect filtering for one particular extension wouldn't make for great UI but just hiding everything that doesn't use any would be nice.

### PR DESCRIPTION
**Pull request by Meivyn**
This adds a new filter for mods requirements, so you can easily find all wall maps and the like that rely on Chroma, Noodle Extensions, and Mapping Extensions.

This PR adds CustomJSONData as a dependency, so it's up to you to decide if this is something that bothers you or not.

Closes #147

### CODE REVIEW

**Comment by halsafar** [comment]
Thanks for the PR.

Review looks good.  I'll test this out later today.  I see no problem adding CustomJSONData as a dependency.

**Comment by halsafar** [comment]
Testing seems good!  With only three extensions types we might want to extend this to have a unique filter for each but for now this is good.

**Comment by Meivyn** [comment]
The best would be a submenu for filters just like the "filter by" submenu, so you can also filter by specific difficulty if you merge the other PR.

**Comment by halsafar** [comment]
Agreed.  The filters need a rework exactly as you say.  Should be able to support multiple filters as well.  Something I'll start on soon. In the mean time this is a nice addition and I'll get it out with the next release.

**Comment by Meivyn** [comment]
Any news about this PR? Either you forget every time (I saw your posts on the difficulty filter, it was fun to read) or you still have concerns about it. If so, please tell me.

**Comment by halsafar** [comment]
It was merged after the last release, simply forgot to push.  It is live now in master.

**Pull request merged**
