### PR TITLE
Added filters for Difficulties

### PR DESCRIPTION
**Pull request by brianhuang822**
Added filters for Difficulties. Resolves https://github.com/halsafar/BeatSaberSongBrowser/issues/118 and Resolves https://github.com/halsafar/BeatSaberSongBrowser/issues/114 to some degree

### CODE REVIEW

**Comment by halsafar** [comment]
This looks excellent!  I am just going to give it a spin and then I'll merge it in.

Thanks for this PR @brianhuang822.  I'll get you on the authors list.

**Comment by halsafar** [comment]
Going to be doing another release in a few days.  Will try to get this PR in finally.  Sorry for the delay.

**Comment by SpencerGraffunder** [comment]
I would love to have this in the game. Bump?

**Comment by winterNebs** [comment]
Was looking around for more info on a way to filter by difficulty and found this, not to necro but this would be a super great QOL improvement

**Comment by JonnyVR1** [comment]
Hi all, I have ported this addition to the latest version of the mod as seen here https://github.com/halsafar/BeatSaberSongBrowser/pull/190

**Comment by halsafar** [comment]
This is merged into the next release.

**Pull request closed without merging**
