### PR TITLE
Changed list to BeatStar and reflected that change in loading message

### PR DESCRIPTION
**Pull request by WesVleuten**
I'm creating a bot that collects pp information and songs. This PR will connect the BeatSaberSongBrowser to that bot to make sure it stays up to date on PP sorting.

### CODE REVIEW

**Comment by halsafar** [comment]
Hey WesVleuten.  This is awesome if you want to take over the PP scraping.  I won't have time to test this for a few days.  Have you given it a good shaking?  Now would be a good time to improve the json format if you have anything better in mind.  Otherwise looks good to merge.

**Comment by WesVleuten** [comment]
Good point, there are a lot of optimizations possible regarding the json. You can expect some new commits from me soon.

**Comment by halsafar** [comment]
Let's get this puppy merged in immediately though.  I see no issues with it.

**Comment by WesVleuten** [comment]
That's OK. I'm still working on optimization. But I'll make another PR for that!

**Pull request merged**
